### ISSUE TITLE
Add codes in Java Folder

### ISSUE THREAD

**Issue by pratyushmp** [pratyushmp/Hacktoberfest_2k-19#2]

**Comment by manimanasamylavarapu** [comment]
can u please assign this to me

**Comment by manimanasamylavarapu** [comment]
Hi @pratyushmp 
create a pr 
https://github.com/pratyushmp/Hacktoberfest_2k-19/pull/38

Can I create more pr for same issue. I mean adding more algorithms

**Comment by pratyushmp** [comment]
Yeah Sure! Keep Contributing as much as you like.

**Comment by manimanasamylavarapu** [comment]
@pratyushmp thanks for reviewing and merging the PRs. Quick ques, do I have to do anything to mark these PRs as hacktoberfest contribution?

**Comment by pratyushmp** [comment]
Nope they get automatically counted. You can go and check at https://hacktoberfest.digitalocean.com

**Comment by pratyushmp** [comment]
Nope they get counted automatically. You can check your progress at https://hacktoberfest.digitalocean.com

**Comment by pratyushmp** [comment]
Nope they get counted automatically. You can go and check your progress at https://hacktoberfest.digitalocean.com

**Comment by JithendraD** [comment]
hey @pratyushmp, can multiple contribute to the same issue- I'd like to contribute to this issue

**Comment by pratyushmp** [comment]
Yes you can! Contribute freely :)

**Comment by jjz13744** [comment]
#45

**Comment by jjz13744** [comment]
#45 **Created a program that can convert decimal to binary and binary to decimal.**
